name: CI

on:
  workflow_dispatch:
  push:
    branches: [master, experimental]
    paths-ignore:
      - '**/*.md'
      - '**/*.html'
      - '**/*.png'
      - '**/*.bmp'
      - '**/LICENSE*'
      - '**/license*'
      - '**/README*'
      - '**/ReadMe*'
      - '**/INSTALL*'
      - '**/AUTHORS'
      - '**/COPYING'
  pull_request:
    branches: [master, experimental]
    paths-ignore:
      - '**/*.md'
      - '**/*.html'
      - '**/*.png'
      - '**/*.bmp'
      - '**/LICENSE*'
      - '**/license*'
      - '**/README*'
      - '**/ReadMe*'
      - '**/INSTALL*'
      - '**/AUTHORS'
      - '**/COPYING'

jobs:
  Build_x64:
    runs-on: windows-2022
    timeout-minutes: 45

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v2

      - name: Build Sandboxie x86 (DLLs & svc)
        run: msbuild /t:build Sandboxie\SandboxDll.sln /p:Configuration="SbieRelease" /p:Platform=Win32 -maxcpucount:8

      - name: Build Sandboxie x64 (all)
        run: msbuild /t:build Sandboxie\Sandbox.sln /p:Configuration="SbieRelease" /p:Platform=x64 -maxcpucount:8
        
      - name: Build Sandboxie x64 (drv)
        run: msbuild /t:build Sandboxie\SandboxDrv.sln /p:Configuration="SbieRelease" /p:Platform=x64 -maxcpucount:8

      - name: Prepare output directory
        run: |
          mkdir BuildOutput
          mkdir BuildOutput\x86
          mkdir BuildOutput\x64

      - name: Copy x86 binaries
        run: |
          Copy-Item Sandboxie\Bin\Win32\SbieRelease\*.dll BuildOutput\x86\
          Copy-Item Sandboxie\Bin\Win32\SbieRelease\*.exe BuildOutput\x86\
          if (Test-Path "Sandboxie\core\low\obj\i386\LowLevel.dll") {
            Copy-Item "Sandboxie\core\low\obj\i386\LowLevel.dll" BuildOutput\x86\
          }

      - name: Copy x64 binaries
        run: |
          Copy-Item Sandboxie\Bin\x64\SbieRelease\*.dll BuildOutput\x64\
          Copy-Item Sandboxie\Bin\x64\SbieRelease\*.exe BuildOutput\x64\
          Copy-Item Sandboxie\Bin\x64\SbieRelease\*.sys BuildOutput\x64\
          if (Test-Path "Sandboxie\core\low\obj\amd64\LowLevel.dll") {
            Copy-Item "Sandboxie\core\low\obj\amd64\LowLevel.dll" BuildOutput\x64\
          }

      - name: Copy tools
        run: |
          if (Test-Path "SandboxieTools\Release\*.exe") {
            Copy-Item SandboxieTools\Release\*.exe BuildOutput\x64\
          }

      - name: Upload Sandboxie Build
        uses: actions/upload-artifact@v7.0.0
        with:
          name: Sandboxie-Build-x64
          path: |
            BuildOutput/**
          retention-days: 30
